name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: write
  pages: write
  pull-requests: write
  repository-projects: write
  deployments: write
  checks: write
  actions: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    

    - name : Run Match link generation script
      run: |
        mv index.html match_old.html
        python match.py
        ls -lsrt

    - name: Check for modified files
      id: git-check
      run: echo ::set-output name=modified::$(if [ -n "$(git diff match_old.html index.html)" ]; then echo "true"; else echo "false"; fi)
    
    - name: Generate Match.html
      if: steps.git-check.outputs.modified == 'true'
      run: |
        
        git config --global user.name thivinanandh
        git config --global user.email thivinanandh@gmail.com
        git status
        
        git add index.html
        git commit -m "Automatic Update-1"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
